"""add missing columns to users

Revision ID: 1fca79f7139a
Revises: 058c7f8d498d
Create Date: 2025-10-29 15:40:10.271611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1fca79f7139a'
down_revision: Union[str, Sequence[str], None] = '058c7f8d498d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('gender', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patients_id'), 'patients', ['id'], unique=False)
    op.create_table('assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('ALZHEIMER_DIAGNOSIS', 'ALZHEIMER_RISK', 'CARDIOLOGY_ASCVD', 'CARDIOLOGY_BP', 'CARDIOLOGY_CHA2DS2VASC', 'CARDIOLOGY_ECG', name='assessmenttype'), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('clinician_id', sa.Integer(), nullable=True),
    sa.Column('input_data', sa.JSON(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('algorithm_version', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['clinician_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessments_id'), 'assessments', ['id'], unique=False)
    op.create_index(op.f('ix_assessments_type'), 'assessments', ['type'], unique=False)
    op.add_column('users', sa.Column('company', sa.String(), nullable=True))
    op.add_column('users', sa.Column('team_size', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('enterprise_interest', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('trial_start_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('trial_end_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('stripe_customer_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('subscription_status', sa.String(), nullable=False))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_column('users', 'subscription_status')
    op.drop_column('users', 'stripe_customer_id')
    op.drop_column('users', 'trial_end_date')
    op.drop_column('users', 'trial_start_date')
    op.drop_column('users', 'enterprise_interest')
    op.drop_column('users', 'team_size')
    op.drop_column('users', 'company')
    op.drop_index(op.f('ix_assessments_type'), table_name='assessments')
    op.drop_index(op.f('ix_assessments_id'), table_name='assessments')
    op.drop_table('assessments')
    op.drop_index(op.f('ix_patients_id'), table_name='patients')
    op.drop_table('patients')
    # ### end Alembic commands ###
