"""Change patient_id to string in assessments

Revision ID: 50398906740c
Revises: 1fca79f7139a
Create Date: 2025-11-18 15:04:17.207154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50398906740c'
down_revision: Union[str, Sequence[str], None] = '1fca79f7139a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assessments', 'patient_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               nullable=True)
    op.drop_constraint(op.f('assessments_patient_id_fkey'), 'assessments', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('assessments_patient_id_fkey'), 'assessments', 'patients', ['patient_id'], ['id'])
    op.alter_column('assessments', 'patient_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
