"""
Alzheimer's screening classifier (CN, MCI, AD)
----------------------------------------------
Uses a pre-trained XGBoost pipeline model (preprocessing included).

NOTE:
This module ONLY performs prediction.
Assessment IDs are generated by Supabase when the
assessment record is inserted in the database.
"""

import numpy as np

from app.services.registry import register_assessment
from app.clinical.utils import load_model, build_df_from_order, log_usage

from app.schemas.alzheimer.diagnosis_screening import (
    AlzheimerDiagnosisInput,
    AlzheimerDiagnosisOutput,
)

# -----------------------------
# Constants
# -----------------------------

ASSESSMENT_TYPE = "ALZHEIMER_DIAGNOSIS_SCREENING"

CLASS_NAMES = ["CN", "MCI", "AD"]

FEATURE_ORDER = [
    "age",
    "education_years",
    "moca_score",
    "adas13_score",
    "cdr_sum",
    "faq_total",
    "gender",
    "race",
]

CATEGORICAL_COLS = ["gender", "race"]

MODEL_PATH = "alzheimer/diagnosis_screening/v1/diagnosis_screening_model.joblib"

MODEL_NAME = "Alzheimer_diagnosis_with_CDSUM-v1"
MODEL_VERSION = "1.0.0"

_model_cache = None


def _get_model():
    global _model_cache
    if _model_cache is None:
        _model_cache, _ = load_model(MODEL_PATH)
    return _model_cache


# -----------------------------
# Prediction Function
# -----------------------------

@register_assessment(
    ASSESSMENT_TYPE,
    specialty="alzheimer",
    input_schema=AlzheimerDiagnosisInput,
)
def predict_cognitive_status(
    input_schema: AlzheimerDiagnosisInput,
) -> AlzheimerDiagnosisOutput:

    input_data = input_schema.model_dump(mode="json")

    try:

        # Normalize categorical fields
        for col in CATEGORICAL_COLS:
            input_data[col] = str(input_data.get(col, "unknown")).lower()

        # Validate features
        missing = [f for f in FEATURE_ORDER if f not in input_data]
        if missing:
            raise ValueError(f"Missing required features: {missing}")

        # Build dataframe
        df = build_df_from_order(input_data, FEATURE_ORDER)

        model = _get_model()

        y_proba = model.predict_proba(df)[0]

        y_pred_idx = int(np.argmax(y_proba))
        predicted_class = CLASS_NAMES[y_pred_idx]

        probabilities = {
            cls: float(prob)
            for cls, prob in zip(CLASS_NAMES, y_proba)
        }

        confidence = float(np.max(y_proba))

        log_usage(
            function_name="predict_cognitive_status",
            metadata=input_data,
            result={
                "predicted_class": predicted_class,
                "confidence": confidence,
                "probabilities": probabilities,
            },
        )

        return AlzheimerDiagnosisOutput(
            patient_id=input_schema.patient_id,
            predicted_class=predicted_class,
            confidence=confidence,
            probabilities=probabilities,
            top_features=None,
            model_name=MODEL_NAME,
            model_version=MODEL_VERSION,
        )

    except Exception as e:

        log_usage(
            function_name="predict_cognitive_status_error",
            metadata={"patient_id": getattr(input_schema, "patient_id", None)},
            result={"error": str(e)},
        )

        return AlzheimerDiagnosisOutput(
            patient_id=getattr(input_schema, "patient_id", None),
            predicted_class=None,
            confidence=0.0,
            probabilities={},
            top_features=None,
            model_name=MODEL_NAME,
            model_version=MODEL_VERSION,
            error=str(e),
        )


__all__ = ["predict_cognitive_status"]