"""
Extended Alzheimer's diagnosis classifier (CN, MCI, AD)
-------------------------------------------------------
Uses pre-trained model with numeric, categorical, imaging,
and biomarker preprocessing.

Aligned with AlzheimerDiagnosisExtendedInput schema.

NOTE:
This module ONLY performs prediction.
Assessment IDs are generated by Supabase when the
assessment record is inserted in the database.
"""

import numpy as np

from app.schemas.alzheimer.diagnosis_extended import (
    AlzheimerDiagnosisExtendedInput,
    AlzheimerDiagnosisExtendedOutput,
)

from app.clinical.utils import (
    fill_defaults,
    preprocess_for_prediction,
    load_model,
    log_usage,
)

# -----------------------------
# Constants
# -----------------------------

CLASS_NAMES = ["CN", "MCI", "AD"]

EXTENDED_FEATURE_ORDER = [
    "AGE",
    "MMSE",
    "FAQ",
    "PTEDUCAT",
    "PTGENDER",
    "APOE4",
    "RAVLT_immediate",
    "MOCA",
    "ADAS13",
    "Hippocampus",
    "Ventricles",
    "WholeBrain",
    "Entorhinal",
    "FDG",
    "AV45",
    "PIB",
    "FBB",
    "ABETA",
    "TAU",
    "PTAU",
    "mPACCdigit",
    "mPACCtrailsB",
]

NUMERIC_COLUMNS = [
    col for col in EXTENDED_FEATURE_ORDER
    if col not in ("PTGENDER", "APOE4")
]

CATEGORICAL_COLUMNS = [
    "PTGENDER",
    "APOE4",
]

MODEL_PATH = "alzheimer/diagnosis_extended/v1/diagnosis_extended_model.pkl"
PREPROCESSOR_PATH = "alzheimer/diagnosis_extended/v1/diagnosis_extended_scaler.pkl"

# -----------------------------
# Defaults
# -----------------------------

NUMERIC_DEFAULTS = {
    "AGE": 75.0,
    "MMSE": 28.0,
    "FAQ": 0.0,
    "PTEDUCAT": 16.0,
    "RAVLT_immediate": 40.0,
    "MOCA": 26.0,
    "ADAS13": 10.5,
    "Hippocampus": 3500.0,
    "Ventricles": 40000.0,
    "WholeBrain": 1.0e6,
    "Entorhinal": 3000.0,
    "FDG": 1.1,
    "AV45": 1.0,
    "PIB": 1.0,
    "FBB": 1.0,
    "ABETA": 800.0,
    "TAU": 250.0,
    "PTAU": 25.0,
    "mPACCdigit": 0.0,
    "mPACCtrailsB": 0.0,
}

CATEGORICAL_DEFAULTS = {
    "PTGENDER": "female",
    "APOE4": 0,
}

# -----------------------------
# Prediction Function
# -----------------------------

def predict_cognitive_status_extended(
    input_schema: AlzheimerDiagnosisExtendedInput,
) -> AlzheimerDiagnosisExtendedOutput:
    """
    Predict cognitive status using extended Alzheimer's model.
    """

    input_data = input_schema.model_dump()

    try:

        # Load model + scaler
        model, preprocessor = load_model(
            MODEL_PATH,
            PREPROCESSOR_PATH,
        )

        # Preprocess
        X_scaled = preprocess_for_prediction(
            input_data=input_data,
            numeric_defaults=NUMERIC_DEFAULTS,
            categorical_defaults=CATEGORICAL_DEFAULTS,
            feature_order=EXTENDED_FEATURE_ORDER,
            numeric_columns=NUMERIC_COLUMNS,
            categorical_columns=CATEGORICAL_COLUMNS,
            scaler=preprocessor,
        )

        # Predict
        y_proba = model.predict_proba(X_scaled)[0]
        y_pred_idx = int(np.argmax(y_proba))

        predicted_class = CLASS_NAMES[y_pred_idx]

        probabilities = {
            cls: float(prob)
            for cls, prob in zip(CLASS_NAMES, y_proba)
        }

        confidence = float(np.max(y_proba))

        # Logging metadata
        filled_data = fill_defaults(
            input_data,
            NUMERIC_DEFAULTS,
            CATEGORICAL_DEFAULTS,
        )

        log_usage(
            function_name="predict_cognitive_status_extended",
            metadata={k: filled_data.get(k) for k in EXTENDED_FEATURE_ORDER},
            result={
                "predicted_class": predicted_class,
                "confidence": confidence,
                "probabilities": probabilities,
            },
        )

        return AlzheimerDiagnosisExtendedOutput(
            patient_id=input_schema.patient_id,
            predicted_class=predicted_class,
            confidence=confidence,
            probabilities=probabilities,
            top_features=None,
            model_name="Alzheimer_diagnosis_with_extended_features-v1",
            model_version="1.0.0",
        )

    except Exception as e:

        log_usage(
            function_name="predict_cognitive_status_extended_error",
            metadata={"patient_id": getattr(input_schema, "patient_id", None)},
            result={"error": str(e)},
        )

        return AlzheimerDiagnosisExtendedOutput(
            patient_id=getattr(input_schema, "patient_id", None),
            predicted_class=None,
            confidence=0.0,
            probabilities={},
            top_features=None,
            model_name="Alzheimer_diagnosis_with_extended_features-v1",
            model_version="1.0.0",
            error=str(e),
        )


__all__ = ["predict_cognitive_status_extended"]