from typing import Type
from pydantic import BaseModel

from app.services.pdf_engine.base_pdf import (
    build_pdf,
    title,
    section,
    paragraph,
    spacer,
    table,
)

from app.services.pdf_engine.schema_pdf_builder import schema_to_table
from app.services.pdf_engine.clinical_sections import (
    build_metadata_section,
    build_clinical_interpretation,
)


def generate_assessment_pdf(
    *,
    assessment: dict,
    input_schema: Type[BaseModel],
    output_schema: Type[BaseModel],
    filename: str,
):
    """
    Generate a standardized clinical PDF report
    from an assessment record stored in Supabase.
    """

    elements = []

    input_data = assessment.get("input_data", {})
    output_data = assessment.get("output_data", {})

    # --------------------------------------------------
    # Report Title
    # --------------------------------------------------

    title_text = f"{assessment.get('specialty', '').title()} Clinical Assessment"

    elements.append(title(title_text))
    elements.append(spacer())

    # --------------------------------------------------
    # Metadata
    # --------------------------------------------------

    elements.append(section("Assessment Metadata"))
    elements.append(table(build_metadata_section(assessment)))
    elements.append(spacer())

    # --------------------------------------------------
    # Input Data
    # --------------------------------------------------

    elements.append(section("Patient Inputs"))
    elements.append(
        table(schema_to_table(input_schema, input_data))
    )
    elements.append(spacer())

    # --------------------------------------------------
    # Model Results
    # --------------------------------------------------

    elements.append(section("Model Results"))
    elements.append(
        table(schema_to_table(output_schema, output_data))
    )
    elements.append(spacer())

    # --------------------------------------------------
    # Clinical Interpretation
    # --------------------------------------------------

    interpretation = build_clinical_interpretation(
        assessment.get("assessment_type"),
        output_data,
    )

    if interpretation:
        elements.append(section("Clinical Interpretation"))
        elements.append(paragraph(interpretation))
        elements.append(spacer())

    # --------------------------------------------------
    # Footer
    # --------------------------------------------------

    elements.append(
        paragraph(
            "This report was generated by a clinical decision support model "
            "and should be interpreted alongside professional clinical judgement."
        )
    )

    pdf_path = build_pdf(filename, elements)

    return pdf_path